export enum AppCodes {
  SUCCESS = 1,
  FAILED = -1,
  TOKEN_ALREADY_EXISTS = -2,
  FAILED_FETCHING_TRANSACTIONS,
  FAILED_BUY_TRADE,
  SUCCESS_BUY_TRADE,
  FAILED_SETUP_ASSOCIATED_TOKEN_ACCOUNT,
  SUCCESS_SETUP_ASSOCIATED_TOKEN_ACCOUNT,
  FAILED_GET_ASSOCIATED_TOKEN_ACCOUNT,
  FAILED_GETTING_TOKEN_DATA_FROM_TRANSACTION_SIGNATURE,
  FAILED_SETTING_TOKEN_INFO,
  FAILED_GETTING_BONDING_CURVE,
}
